### ISSUE TITLE
Calling RawBtPrinter intent from adb shell

### ISSUE THREAD

**Issue by Salmon-Bard** [402d/DemoRawBtPrinter#2]
Hi, 
I'm trying to broadcast intent from shell to print html file with no success. 
I used the java code examples as reference but still could not get it to work. 

here is my testing command:
`am broadcast -a ru.a402d.rawbtprinter.action.PRINT_RAWBT  --es DATA "zsfssfsdfsdf"`

Thanks for your kind assistance

**Comment by Muraveiko** [comment]
PRINT_RAWBT not work with adb.
 /**
     * see manifest :
     *    uses-permission android:name="ru.a402d.rawbtprinter.PERMISSION" 
     *
     */
    @OnClick(R.id.test15)
    public void test15(Button button)

app must have permission request in manifest.

**Comment by Salmon-Bard** [comment]
Thanks for the clarification
Got it working at last.

Very Cool and useful project
